package ResellerClub::FundService;
# Generated by SOAP::Lite (v0.710.08) for Perl -- soaplite.com
# Copyright (C) 2000-2006 Paul Kulchenko, Byrne Reese
# -- generated at [Wed Aug 26 01:07:55 2009]
# -- generated from file:wsdl/Fund.wsdl
my %methods = (
addResellerDebitNote => {
    endpoint => 'http://demo.myorderbox.com/anacreon/servlet/APIv3-XML',
    soapaction => '',
    namespace => 'com.logicboxes.foundation.sfnb.management.Fund',
    parameters => [
      SOAP::Data->new(name => 'SERVICE_USERNAME', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PASSWORD', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_ROLE', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_LANGPREF', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PARENTID', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'resellerId', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'sellingAmount', type => 'xsd:double', attr => {}),
      SOAP::Data->new(name => 'accountingAmount', type => 'xsd:double', attr => {}),
      SOAP::Data->new(name => 'conversionRate', type => 'xsd:double', attr => {}),
      SOAP::Data->new(name => 'description', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'debitNoteDate', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'paymentReminderDays', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'transactionKey', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'transactionInfo', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'updateTotalReceipt', type => 'xsd:boolean', attr => {}),
    ], # end parameters
  }, # end addResellerDebitNote
addCustomerDebitNote => {
    endpoint => 'http://demo.myorderbox.com/anacreon/servlet/APIv3-XML',
    soapaction => '',
    namespace => 'com.logicboxes.foundation.sfnb.management.Fund',
    parameters => [
      SOAP::Data->new(name => 'SERVICE_USERNAME', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PASSWORD', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_ROLE', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_LANGPREF', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PARENTID', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'customerId', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'sellingAmount', type => 'xsd:double', attr => {}),
      SOAP::Data->new(name => 'accountingAmount', type => 'xsd:double', attr => {}),
      SOAP::Data->new(name => 'conversionRate', type => 'xsd:double', attr => {}),
      SOAP::Data->new(name => 'description', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'debitNoteDate', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'paymentReminderDays', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'transactionKey', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'transactionInfo', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'updateTotalReceipt', type => 'xsd:boolean', attr => {}),
    ], # end parameters
  }, # end addCustomerDebitNote
addResellerGreedyDebitNote => {
    endpoint => 'http://demo.myorderbox.com/anacreon/servlet/APIv3-XML',
    soapaction => '',
    namespace => 'com.logicboxes.foundation.sfnb.management.Fund',
    parameters => [
      SOAP::Data->new(name => 'SERVICE_USERNAME', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PASSWORD', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_ROLE', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_LANGPREF', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PARENTID', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'resellerId', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'sellingAmount', type => 'xsd:double', attr => {}),
      SOAP::Data->new(name => 'accountingAmount', type => 'xsd:double', attr => {}),
      SOAP::Data->new(name => 'conversionRate', type => 'xsd:double', attr => {}),
      SOAP::Data->new(name => 'description', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'debitNoteDate', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'paymentReminderDays', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'transactionKey', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'transactionInfo', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'updateTotalReceipt', type => 'xsd:boolean', attr => {}),
    ], # end parameters
  }, # end addResellerGreedyDebitNote
listCustomerTransactions => {
    endpoint => 'http://demo.myorderbox.com/anacreon/servlet/APIv3-XML',
    soapaction => '',
    namespace => 'com.logicboxes.foundation.sfnb.management.Fund',
    parameters => [
      SOAP::Data->new(name => 'SERVICE_USERNAME', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PASSWORD', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_ROLE', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_LANGPREF', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PARENTID', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'customerId', type => 'impl:ArrayOf_xsd_int', attr => {}),
      SOAP::Data->new(name => 'customerUserName', type => 'impl:ArrayOf_xsd_string', attr => {}),
      SOAP::Data->new(name => 'type', type => 'impl:ArrayOf_xsd_string', attr => {}),
      SOAP::Data->new(name => 'key', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'typeId', type => 'impl:ArrayOf_xsd_int', attr => {}),
      SOAP::Data->new(name => 'transId', type => 'impl:ArrayOf_xsd_int', attr => {}),
      SOAP::Data->new(name => 'balanceType', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'description', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'amountStartRange', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'amountEndRange', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'fromDate', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'toDate', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'numOfRecordPerPage', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'pageNum', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'orderBy', type => 'impl:ArrayOf_xsd_string', attr => {}),
    ], # end parameters
  }, # end listCustomerTransactions
addCustomerMiscInvoice => {
    endpoint => 'http://demo.myorderbox.com/anacreon/servlet/APIv3-XML',
    soapaction => '',
    namespace => 'com.logicboxes.foundation.sfnb.management.Fund',
    parameters => [
      SOAP::Data->new(name => 'SERVICE_USERNAME', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PASSWORD', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_ROLE', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_LANGPREF', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PARENTID', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'orderId', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'customerId', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'sellingAmount', type => 'xsd:double', attr => {}),
      SOAP::Data->new(name => 'accountingAmount', type => 'xsd:double', attr => {}),
      SOAP::Data->new(name => 'conversionRate', type => 'xsd:double', attr => {}),
      SOAP::Data->new(name => 'description', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'invoiceDate', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'invoiceDueDate', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'invoiceDeletionDate', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'paymentReminderDays', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'transactionKey', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end addCustomerMiscInvoice
getCustomerGreedyTransactions => {
    endpoint => 'http://demo.myorderbox.com/anacreon/servlet/APIv3-XML',
    soapaction => '',
    namespace => 'com.logicboxes.foundation.sfnb.management.Fund',
    parameters => [
      SOAP::Data->new(name => 'SERVICE_USERNAME', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PASSWORD', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_ROLE', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_LANGPREF', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PARENTID', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'customerId', type => 'xsd:int', attr => {}),
    ], # end parameters
  }, # end getCustomerGreedyTransactions
addResellerGreedyMiscInvoice => {
    endpoint => 'http://demo.myorderbox.com/anacreon/servlet/APIv3-XML',
    soapaction => '',
    namespace => 'com.logicboxes.foundation.sfnb.management.Fund',
    parameters => [
      SOAP::Data->new(name => 'SERVICE_USERNAME', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PASSWORD', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_ROLE', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_LANGPREF', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PARENTID', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'orderId', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'resellerId', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'sellingAmount', type => 'xsd:double', attr => {}),
      SOAP::Data->new(name => 'accountingAmount', type => 'xsd:double', attr => {}),
      SOAP::Data->new(name => 'conversionRate', type => 'xsd:double', attr => {}),
      SOAP::Data->new(name => 'description', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'invoiceDate', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'invoiceDueDate', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'invoiceDeletionDate', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'paymentReminderDays', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'transactionKey', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end addResellerGreedyMiscInvoice
payCustomerTransaction => {
    endpoint => 'http://demo.myorderbox.com/anacreon/servlet/APIv3-XML',
    soapaction => '',
    namespace => 'com.logicboxes.foundation.sfnb.management.Fund',
    parameters => [
      SOAP::Data->new(name => 'SERVICE_USERNAME', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PASSWORD', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_ROLE', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_LANGPREF', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PARENTID', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'invoiceTransIdArr', type => 'impl:ArrayOf_xsd_int', attr => {}),
      SOAP::Data->new(name => 'debitNoteIdArr', type => 'impl:ArrayOf_xsd_int', attr => {}),
    ], # end parameters
  }, # end payCustomerTransaction
addCustomerFund => {
    endpoint => 'http://demo.myorderbox.com/anacreon/servlet/APIv3-XML',
    soapaction => '',
    namespace => 'com.logicboxes.foundation.sfnb.management.Fund',
    parameters => [
      SOAP::Data->new(name => 'SERVICE_USERNAME', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PASSWORD', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_ROLE', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_LANGPREF', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PARENTID', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'customerId', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'sellingAmount', type => 'xsd:double', attr => {}),
      SOAP::Data->new(name => 'description', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'type', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'transactionKey', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'updateTotalReceipt', type => 'xsd:boolean', attr => {}),
    ], # end parameters
  }, # end addCustomerFund
addResellerFund => {
    endpoint => 'http://demo.myorderbox.com/anacreon/servlet/APIv3-XML',
    soapaction => '',
    namespace => 'com.logicboxes.foundation.sfnb.management.Fund',
    parameters => [
      SOAP::Data->new(name => 'SERVICE_USERNAME', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PASSWORD', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_ROLE', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_LANGPREF', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PARENTID', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'resellerId', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'sellingAmount', type => 'xsd:double', attr => {}),
      SOAP::Data->new(name => 'description', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'type', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'transactionKey', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'updateTotalReceipt', type => 'xsd:boolean', attr => {}),
    ], # end parameters
  }, # end addResellerFund
getDeletedRefundDetails => {
    endpoint => 'http://demo.myorderbox.com/anacreon/servlet/APIv3-XML',
    soapaction => '',
    namespace => 'com.logicboxes.foundation.sfnb.management.Fund',
    parameters => [
      SOAP::Data->new(name => 'SERVICE_USERNAME', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PASSWORD', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_ROLE', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_LANGPREF', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PARENTID', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'customerId', type => 'impl:ArrayOf_xsd_int', attr => {}),
      SOAP::Data->new(name => 'refundId', type => 'impl:ArrayOf_xsd_int', attr => {}),
      SOAP::Data->new(name => 'status', type => 'impl:ArrayOf_xsd_string', attr => {}),
      SOAP::Data->new(name => 'numOfRecordPerPage', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'pageNum', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'orderBy', type => 'impl:ArrayOf_xsd_string', attr => {}),
    ], # end parameters
  }, # end getDeletedRefundDetails
addCustomerGreedyDebitNote => {
    endpoint => 'http://demo.myorderbox.com/anacreon/servlet/APIv3-XML',
    soapaction => '',
    namespace => 'com.logicboxes.foundation.sfnb.management.Fund',
    parameters => [
      SOAP::Data->new(name => 'SERVICE_USERNAME', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PASSWORD', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_ROLE', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_LANGPREF', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PARENTID', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'customerId', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'sellingAmount', type => 'xsd:double', attr => {}),
      SOAP::Data->new(name => 'accountingAmount', type => 'xsd:double', attr => {}),
      SOAP::Data->new(name => 'conversionRate', type => 'xsd:double', attr => {}),
      SOAP::Data->new(name => 'description', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'debitNoteDate', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'paymentReminderDays', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'transactionKey', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'transactionInfo', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'updateTotalReceipt', type => 'xsd:boolean', attr => {}),
    ], # end parameters
  }, # end addCustomerGreedyDebitNote
listResellerTransactions => {
    endpoint => 'http://demo.myorderbox.com/anacreon/servlet/APIv3-XML',
    soapaction => '',
    namespace => 'com.logicboxes.foundation.sfnb.management.Fund',
    parameters => [
      SOAP::Data->new(name => 'SERVICE_USERNAME', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PASSWORD', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_ROLE', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_LANGPREF', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PARENTID', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'resellerId', type => 'impl:ArrayOf_xsd_int', attr => {}),
      SOAP::Data->new(name => 'resellerUserName', type => 'impl:ArrayOf_xsd_string', attr => {}),
      SOAP::Data->new(name => 'type', type => 'impl:ArrayOf_xsd_string', attr => {}),
      SOAP::Data->new(name => 'key', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'typeId', type => 'impl:ArrayOf_xsd_int', attr => {}),
      SOAP::Data->new(name => 'transId', type => 'impl:ArrayOf_xsd_int', attr => {}),
      SOAP::Data->new(name => 'balanceType', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'description', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'amountStartRange', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'amountEndRange', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'fromDate', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'toDate', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'numOfRecordPerPage', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'pageNum', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'orderBy', type => 'impl:ArrayOf_xsd_string', attr => {}),
    ], # end parameters
  }, # end listResellerTransactions
executeWithoutPayment => {
    endpoint => 'http://demo.myorderbox.com/anacreon/servlet/APIv3-XML',
    soapaction => '',
    namespace => 'com.logicboxes.foundation.sfnb.management.Fund',
    parameters => [
      SOAP::Data->new(name => 'SERVICE_USERNAME', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PASSWORD', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_ROLE', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_LANGPREF', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PARENTID', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'invoiceTransId', type => 'impl:ArrayOf_xsd_int', attr => {}),
      SOAP::Data->new(name => 'cancelInvoice', type => 'xsd:boolean', attr => {}),
    ], # end parameters
  }, # end executeWithoutPayment
getCustomerAvailableBalance => {
    endpoint => 'http://demo.myorderbox.com/anacreon/servlet/APIv3-XML',
    soapaction => '',
    namespace => 'com.logicboxes.foundation.sfnb.management.Fund',
    parameters => [
      SOAP::Data->new(name => 'SERVICE_USERNAME', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PASSWORD', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_ROLE', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_LANGPREF', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PARENTID', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'customerId', type => 'xsd:int', attr => {}),
    ], # end parameters
  }, # end getCustomerAvailableBalance
addCustomerGreedyMiscInvoice => {
    endpoint => 'http://demo.myorderbox.com/anacreon/servlet/APIv3-XML',
    soapaction => '',
    namespace => 'com.logicboxes.foundation.sfnb.management.Fund',
    parameters => [
      SOAP::Data->new(name => 'SERVICE_USERNAME', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PASSWORD', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_ROLE', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_LANGPREF', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PARENTID', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'orderId', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'customerId', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'sellingAmount', type => 'xsd:double', attr => {}),
      SOAP::Data->new(name => 'accountingAmount', type => 'xsd:double', attr => {}),
      SOAP::Data->new(name => 'conversionRate', type => 'xsd:double', attr => {}),
      SOAP::Data->new(name => 'description', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'invoiceDate', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'invoiceDueDate', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'invoiceDeletionDate', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'paymentReminderDays', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'transactionKey', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end addCustomerGreedyMiscInvoice
getCustomerTransactionDetails => {
    endpoint => 'http://demo.myorderbox.com/anacreon/servlet/APIv3-XML',
    soapaction => '',
    namespace => 'com.logicboxes.foundation.sfnb.management.Fund',
    parameters => [
      SOAP::Data->new(name => 'SERVICE_USERNAME', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PASSWORD', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_ROLE', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_LANGPREF', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PARENTID', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'transId', type => 'xsd:int', attr => {}),
    ], # end parameters
  }, # end getCustomerTransactionDetails
listBalancedTransactions => {
    endpoint => 'http://demo.myorderbox.com/anacreon/servlet/APIv3-XML',
    soapaction => '',
    namespace => 'com.logicboxes.foundation.sfnb.management.Fund',
    parameters => [
      SOAP::Data->new(name => 'SERVICE_USERNAME', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PASSWORD', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_ROLE', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_LANGPREF', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PARENTID', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'transId', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'forRole', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end listBalancedTransactions
addResellerMiscInvoice => {
    endpoint => 'http://demo.myorderbox.com/anacreon/servlet/APIv3-XML',
    soapaction => '',
    namespace => 'com.logicboxes.foundation.sfnb.management.Fund',
    parameters => [
      SOAP::Data->new(name => 'SERVICE_USERNAME', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PASSWORD', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_ROLE', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_LANGPREF', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PARENTID', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'orderId', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'resellerId', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'sellingAmount', type => 'xsd:double', attr => {}),
      SOAP::Data->new(name => 'accountingAmount', type => 'xsd:double', attr => {}),
      SOAP::Data->new(name => 'conversionRate', type => 'xsd:double', attr => {}),
      SOAP::Data->new(name => 'description', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'invoiceDate', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'invoiceDueDate', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'invoiceDeletionDate', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'paymentReminderDays', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'transactionKey', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end addResellerMiscInvoice
getResellerGreedyTransactions => {
    endpoint => 'http://demo.myorderbox.com/anacreon/servlet/APIv3-XML',
    soapaction => '',
    namespace => 'com.logicboxes.foundation.sfnb.management.Fund',
    parameters => [
      SOAP::Data->new(name => 'SERVICE_USERNAME', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PASSWORD', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_ROLE', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_LANGPREF', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PARENTID', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'resellerId', type => 'xsd:int', attr => {}),
    ], # end parameters
  }, # end getResellerGreedyTransactions
getTransactionDetails => {
    endpoint => 'http://demo.myorderbox.com/anacreon/servlet/APIv3-XML',
    soapaction => '',
    namespace => 'com.logicboxes.foundation.sfnb.management.Fund',
    parameters => [
      SOAP::Data->new(name => 'SERVICE_USERNAME', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PASSWORD', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_ROLE', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_LANGPREF', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'SERVICE_PARENTID', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'ids', type => 'impl:ArrayOf_xsd_int', attr => {}),
      SOAP::Data->new(name => 'role', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getTransactionDetails
); # end my %methods

use SOAP::Lite;
use Exporter;
use Carp ();

use vars qw(@ISA $AUTOLOAD @EXPORT_OK %EXPORT_TAGS);
@ISA = qw(Exporter SOAP::Lite);
@EXPORT_OK = (keys %methods);
%EXPORT_TAGS = ('all' => [@EXPORT_OK]);

sub _call {
    my ($self, $method) = (shift, shift);
    my $name = UNIVERSAL::isa($method => 'SOAP::Data') ? $method->name : $method;
    my %method = %{$methods{$name}};
    $self->proxy($method{endpoint} || Carp::croak "No server address (proxy) specified")
        unless $self->proxy;
    my @templates = @{$method{parameters}};
    my @parameters = ();
    foreach my $param (@_) {
        if (@templates) {
            my $template = shift @templates;
            my ($prefix,$typename) = SOAP::Utils::splitqname($template->type);
            my $method = 'as_'.$typename;
            # TODO - if can('as_'.$typename) {...}
            my $result = $self->serializer->$method($param, $template->name, $template->type, $template->attr);
            push(@parameters, $template->value($result->[2]));
        }
        else {
            push(@parameters, $param);
        }
    }
    $self->endpoint($method{endpoint})
       ->ns($method{namespace})
       ->on_action(sub{qq!"$method{soapaction}"!});
  $self->serializer->register_ns("com.logicboxes.foundation.sfnb.management.Fund","impl");
  $self->serializer->register_ns("http://schemas.xmlsoap.org/wsdl/soap/","wsdlsoap");
  $self->serializer->register_ns("http://xml.apache.org/xml-soap","apachesoap");
  $self->serializer->register_ns("http://schemas.xmlsoap.org/wsdl/","wsdl");
  $self->serializer->register_ns("http://schemas.xmlsoap.org/soap/encoding/","soapenc");
  $self->serializer->register_ns("http://www.w3.org/2001/XMLSchema","xsd");
    my $som = $self->SUPER::call($method => @parameters);
    if ($self->want_som) {
        return $som;
    }
    UNIVERSAL::isa($som => 'SOAP::SOM') ? wantarray ? $som->paramsall : $som->result : $som;
}

sub BEGIN {
    no strict 'refs';
    for my $method (qw(want_som)) {
        my $field = '_' . $method;
        *$method = sub {
            my $self = shift->new;
            @_ ? ($self->{$field} = shift, return $self) : return $self->{$field};
        }
    }
}
no strict 'refs';
for my $method (@EXPORT_OK) {
    my %method = %{$methods{$method}};
    *$method = sub {
        my $self = UNIVERSAL::isa($_[0] => __PACKAGE__)
            ? ref $_[0]
                ? shift # OBJECT
                # CLASS, either get self or create new and assign to self
                : (shift->self || __PACKAGE__->self(__PACKAGE__->new))
            # function call, either get self or create new and assign to self
            : (__PACKAGE__->self || __PACKAGE__->self(__PACKAGE__->new));
        $self->_call($method, @_);
    }
}

sub AUTOLOAD {
    my $method = substr($AUTOLOAD, rindex($AUTOLOAD, '::') + 2);
    return if $method eq 'DESTROY' || $method eq 'want_som';
    die "Unrecognized method '$method'. List of available method(s): @EXPORT_OK\n";
}

1;
